"""Generate Planning/GANTT.md (a Mermaid gantt chart) from Planning/schedule.yaml.

Mermaid `gantt` blocks render natively on GitHub and in Obsidian, so the chart is just
Markdown — no image build step. `schedule.yaml` is the source-of-truth; GANTT.md is
generated and should not be hand-edited.

Usage:
    uv run python Planning/build_gantt.py
    uv run python Planning/build_gantt.py --dry-run     # print, don't write

Task schema (see schedule.yaml for the authored form):
    name      (required)  task label
    start     (required)  YYYY-MM-DD
    end       /           explicit end date YYYY-MM-DD
    duration  (one of)    "8w" | "90d" | "3m" | "2y"  (mutually exclusive with end)
    type      (optional)  task (default) | milestone | active | done | crit
    id        (optional)  stable id (auto-derived from name if omitted)
"""

import argparse
import re
import sys
from pathlib import Path

import yaml

PLANNING_DIR = Path(__file__).resolve().parent
SCHEDULE = PLANNING_DIR / "schedule.yaml"
OUTPUT = PLANNING_DIR / "GANTT.md"

# Mermaid understands these status tags directly; "milestone" is handled separately.
STATUS_TAGS = {"active", "done", "crit"}


def slug(name: str) -> str:
    s = re.sub(r"[^a-zA-Z0-9]+", "_", name.strip().lower()).strip("_")
    return s or "task"


def fmt_duration(d: str) -> str:
    """Pass Mermaid-native units through; expand months/years to days (~30/365)."""
    d = str(d).strip()
    m = re.fullmatch(r"(\d+)\s*([dwmy])", d)
    if not m:
        return d  # let Mermaid try; if it's already 'YYYY-MM-DD' end form, fine
    n, unit = int(m.group(1)), m.group(2)
    if unit in ("d", "w"):
        return f"{n}{unit}"
    if unit == "m":
        return f"{n * 30}d"
    if unit == "y":
        return f"{n * 365}d"
    return d


def render_task(task: dict, used_ids: set[str]) -> str:
    name = task.get("name")
    if not name:
        raise ValueError(f"task missing 'name': {task!r}")
    start = task.get("start")
    if not start:
        raise ValueError(f"task {name!r} missing 'start'")

    ttype = task.get("type", "task")

    tid = task.get("id") or slug(name)
    base, i = tid, 2
    while tid in used_ids:
        tid = f"{base}_{i}"
        i += 1
    used_ids.add(tid)

    # Mermaid metadata fields after the colon, comma-separated.
    meta: list[str] = []
    if ttype == "milestone":
        meta.append("milestone")
    elif ttype in STATUS_TAGS:
        meta.append(ttype)

    meta.append(tid)
    meta.append(str(start))

    if ttype == "milestone":
        meta.append("0d")
    elif task.get("end"):
        meta.append(str(task["end"]))
    elif task.get("duration"):
        meta.append(fmt_duration(task["duration"]))
    else:
        raise ValueError(f"task {name!r} needs 'end' or 'duration' (unless milestone)")

    return f"    {name} :{', '.join(meta)}"


def build(schedule: dict) -> str:
    title = schedule.get("title", "PhD timeline")
    date_format = schedule.get("date_format", "YYYY-MM-DD")
    axis_format = schedule.get("axis_format", "%Y-%m")

    lines = ["```mermaid", "gantt", f"    title {title}",
             f"    dateFormat {date_format}", f"    axisFormat {axis_format}"]

    used_ids: set[str] = set()
    for section in schedule.get("sections", []):
        lines.append(f"    section {section.get('name', 'Section')}")
        for task in section.get("tasks", []):
            lines.append(render_task(task, used_ids))
    lines.append("```")

    chart = "\n".join(lines)
    return (
        "<!-- GENERATED by Planning/build_gantt.py from schedule.yaml — do not hand-edit. -->\n"
        "<!-- Regenerate: uv run python Planning/build_gantt.py -->\n\n"
        f"# {title} — Gantt\n\n"
        f"{chart}\n\n"
        "See [schedule.yaml](schedule.yaml) for the source, "
        "[milestones.md](milestones.md) and [deliverables.md](deliverables.md) for detail.\n"
    )


def main() -> int:
    p = argparse.ArgumentParser(description="schedule.yaml → GANTT.md (Mermaid).")
    p.add_argument("--dry-run", action="store_true", help="print instead of writing")
    args = p.parse_args()

    if not SCHEDULE.exists():
        print(f"error: {SCHEDULE} not found", file=sys.stderr)
        return 1

    schedule = yaml.safe_load(SCHEDULE.read_text(encoding="utf-8")) or {}
    try:
        md = build(schedule)
    except ValueError as e:
        print(f"error: {e}", file=sys.stderr)
        return 1

    if args.dry_run:
        print(md)
    else:
        OUTPUT.write_text(md, encoding="utf-8")
        print(f"wrote {OUTPUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
