"""Generate bibliography.bib from the YAML-frontmatter cite-cards.

Walks every `.md` under `Bibliography/Primary/` and `Bibliography/Secondary/`, reads its
YAML frontmatter, and emits a single BibTeX file — one entry per cite-card. The YAML is
canonical; `bibliography.bib` is gitignored and fully regenerable.

Usage:
    uv run python Literature/Bibliography/build_bibtex.py
    uv run python Literature/Bibliography/build_bibtex.py --dry-run

A cite-card missing a required field (cite_key, title, authors, year) is skipped with a
warning to stderr; the script does not abort.
"""

import argparse
import re
import sys
from pathlib import Path

import yaml

BIB_DIR = Path(__file__).resolve().parent
DEFAULT_OUTPUT = BIB_DIR / "bibliography.bib"
FRONTMATTER_RE = re.compile(r"^---\n(.*?)\n---", re.DOTALL)

# Our `kind` → BibTeX entry type.
KIND_TO_ENTRY = {
    "article": "article",
    "book": "book",
    "inproceedings": "inproceedings",
    "thesis": "phdthesis",
    "preprint": "misc",
    "dataset": "misc",
    "misc": "misc",
}


def parse_frontmatter(md_path: Path) -> dict | None:
    text = md_path.read_text(encoding="utf-8")
    m = FRONTMATTER_RE.match(text)
    if not m:
        return None
    try:
        return yaml.safe_load(m.group(1)) or {}
    except yaml.YAMLError as e:
        print(f"YAML error in {md_path}: {e}", file=sys.stderr)
        return None


def format_authors(authors: list[str]) -> str:
    """BibTeX author field: 'Last, First and Last, First'."""
    out = []
    for a in authors:
        a = a.strip()
        if "," in a:
            out.append(a)
        else:
            parts = a.split()
            if len(parts) >= 2:
                out.append(f"{parts[-1]}, {' '.join(parts[:-1])}")
            else:
                out.append(a)
    return " and ".join(out)


def entry_for(fm: dict, src: Path) -> str | None:
    key = fm.get("cite_key")
    missing = [f for f in ("cite_key", "title", "authors", "year") if not fm.get(f)]
    if missing:
        print(f"skip {src.name}: missing {', '.join(missing)}", file=sys.stderr)
        return None

    entry_type = KIND_TO_ENTRY.get(fm.get("kind", "article"), "article")
    fields: list[tuple[str, str]] = [
        ("title", f"{{{fm['title']}}}"),
        ("author", format_authors(fm["authors"])),
        ("year", str(fm["year"])),
    ]
    for yaml_key, bib_key in (
        ("journal", "journal"),
        ("volume", "volume"),
        ("issue", "number"),
        ("pages", "pages"),
        ("doi", "doi"),
        ("url", "url"),
    ):
        val = fm.get(yaml_key)
        if val not in (None, "", []):
            fields.append((bib_key, str(val)))

    if fm.get("arxiv_id"):
        fields.append(("eprint", str(fm["arxiv_id"])))
        fields.append(("archivePrefix", "arXiv"))

    body = ",\n".join(f"  {k} = {{{v}}}" if not v.startswith("{") else f"  {k} = {v}"
                      for k, v in fields)
    return f"@{entry_type}{{{key},\n{body}\n}}"


def main() -> int:
    p = argparse.ArgumentParser(description="Build bibliography.bib from cite-cards.")
    p.add_argument("--dry-run", action="store_true", help="print to stdout instead of writing")
    p.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    args = p.parse_args()

    entries = []
    for sub in ("Primary", "Secondary"):
        for md in sorted((BIB_DIR / sub).glob("*.md")):
            if md.name.startswith("_"):
                continue
            fm = parse_frontmatter(md)
            if fm is None:
                continue
            e = entry_for(fm, md)
            if e:
                entries.append(e)

    out = "% Generated by build_bibtex.py — do not edit. The YAML cite-cards are canonical.\n\n"
    out += "\n\n".join(entries) + ("\n" if entries else "")

    if args.dry_run:
        print(out)
    else:
        args.output.write_text(out, encoding="utf-8")
        print(f"wrote {args.output} ({len(entries)} entries)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
